# Generated by Django 4.0.1 on 2022-03-01 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='data_de_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
